//AUTOGENERATED FILE FROM png2asset
// Conversion args: /carpet.png -sw 16 -sh 16 -o carpet.c

#ifndef METASPRITE_carpet_H
#define METASPRITE_carpet_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define carpet_TILE_ORIGIN 0
#define carpet_TILE_W 8
#define carpet_TILE_H 16
#define carpet_WIDTH 16
#define carpet_HEIGHT 16
#define carpet_TILE_COUNT 2
#define carpet_PALETTE_COUNT 1
#define carpet_COLORS_PER_PALETTE 4
#define carpet_TOTAL_COLORS 4
#define carpet_PIVOT_X 8
#define carpet_PIVOT_Y 8
#define carpet_PIVOT_W 16
#define carpet_PIVOT_H 16
extern const metasprite_t* const carpet_metasprites[1];

BANKREF_EXTERN(carpet)

extern const palette_color_t carpet_palettes[4];
extern const uint8_t carpet_tiles[32];

#endif
