//AUTOGENERATED FILE FROM png2asset
// Conversion args: /carpet.png -sw 16 -sh 16 -o carpet.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(carpet)

const palette_color_t carpet_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(155, 97,165), RGB8(109, 68,115), RGB8( 62, 39, 66)
	};

const uint8_t carpet_tiles[32] = {
	0x00,0x00,0x1f,0x1f,0x30,0x3f,0x27,0x38,0x2c,0x33,0x29,0x36,0x2b,0x34,0x2b,0x35,
	0x2b,0x35,0x2b,0x34,0x29,0x36,0x2c,0x33,0x27,0x38,0x30,0x3f,0x1f,0x1f,0x00,0x00
	};

const metasprite_t carpet_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(0)),
	METASPR_ITEM(0, 8, 0, S_PAL(0) | S_FLIPX),
	METASPR_TERM
};

const metasprite_t* const carpet_metasprites[1] = {
	carpet_metasprite0
};
