//AUTOGENERATED FILE FROM png2asset
// Conversion args: letters.png -sw 16 -sh 16

#ifndef METASPRITE_letters_H
#define METASPRITE_letters_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define letters_TILE_ORIGIN 4
#define letters_TILE_W 8
#define letters_TILE_H 16
#define letters_WIDTH 16
#define letters_HEIGHT 16
#define letters_TILE_COUNT 16
#define letters_PALETTE_COUNT 1
#define letters_COLORS_PER_PALETTE 4
#define letters_TOTAL_COLORS 4
#define letters_PIVOT_X 8
#define letters_PIVOT_Y 8
#define letters_PIVOT_W 16
#define letters_PIVOT_H 16
extern const metasprite_t* const letters_metasprites[4];

BANKREF_EXTERN(letters)

extern const palette_color_t letters_palettes[4];
extern const uint8_t letters_tiles[256];

#endif
