//AUTOGENERATED FILE FROM png2asset
// Conversion args: /RPG_exterior_example.png -o map.c -map

#ifndef METASPRITE_map_H
#define METASPRITE_map_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define map_TILE_ORIGIN 0
#define map_TILE_W 8
#define map_TILE_H 8
#define map_WIDTH 384
#define map_HEIGHT 192
#define map_TILE_COUNT 246
#define map_PALETTE_COUNT 1
#define map_COLORS_PER_PALETTE 4
#define map_TOTAL_COLORS 4
#define map_MAP_ATTRIBUTES 0
extern const unsigned char map_map[1152];
#define map_map_attributes map_map

BANKREF_EXTERN(map)

extern const palette_color_t map_palettes[4];
extern const uint8_t map_tiles[3936];

#endif
