//AUTOGENERATED FILE FROM png2asset
// Conversion args: /wizard.png -sw 16 -sh 16 -o wizard.c

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(wizard)

const palette_color_t wizard_palettes[4] = {
	RGB8(  0,  0,  0), RGB8(255,197,  0), RGB8(179,138,  0), RGB8(102, 79,  0)
	};

const uint8_t wizard_tiles[32] = {
	0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x07,0x00,0x0c,0x03,0x09,0x07,0x0b,0x07,
	0x0b,0x07,0x09,0x07,0x0c,0x03,0x07,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00
	};

const metasprite_t wizard_metasprite0[] = {
	METASPR_ITEM(-8, -8, 0, S_PAL(1)),
	METASPR_ITEM(0, 8, 0, S_PAL(1) | S_FLIPX),
	METASPR_TERM
};

const metasprite_t* const wizard_metasprites[1] = {
	wizard_metasprite0
};
