//AUTOGENERATED FILE FROM png2asset
// Conversion args: /boss.png -sw 16 -sh 16

#ifndef METASPRITE_boss_H
#define METASPRITE_boss_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define boss_TILE_ORIGIN 18
#define boss_TILE_W 8
#define boss_TILE_H 16
#define boss_WIDTH 16
#define boss_HEIGHT 16
#define boss_TILE_COUNT 12
#define boss_PALETTE_COUNT 1
#define boss_COLORS_PER_PALETTE 4
#define boss_TOTAL_COLORS 4
#define boss_PIVOT_X 8
#define boss_PIVOT_Y 8
#define boss_PIVOT_W 16
#define boss_PIVOT_H 16
extern const metasprite_t* const boss_metasprites[4];

BANKREF_EXTERN(boss)

extern const palette_color_t boss_palettes[4];
extern const uint8_t boss_tiles[192];

#endif
