//AUTOGENERATED FILE FROM png2asset
// Conversion args: /heart_filled.png -map -tile_origin 34

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(heart_filled)

const palette_color_t heart_filled_palettes[4] = {
	RGB8(255,255,255), RGB8( 58,255, 91), RGB8(255,  0, 25), RGB8(  0,  0,  0)
	};

const uint8_t heart_filled_tiles[16] = {
	0x66,0x00,0x99,0x66,0x00,0xff,0x00,0xff,0x81,0x7e,0x42,0x3c,0x24,0x18,0x18,0x00
	};


const unsigned char heart_filled_map[1] = {
	0x22,
};
