//AUTOGENERATED FILE FROM png2asset
// Conversion args: /heart.png -map

#ifndef METASPRITE_heart_H
#define METASPRITE_heart_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define heart_TILE_ORIGIN 32
#define heart_TILE_W 8
#define heart_TILE_H 8
#define heart_WIDTH 8
#define heart_HEIGHT 8
#define heart_TILE_COUNT 1
#define heart_PALETTE_COUNT 1
#define heart_COLORS_PER_PALETTE 4
#define heart_TOTAL_COLORS 4
#define heart_MAP_ATTRIBUTES 0
extern const unsigned char heart_map[1];
#define heart_map_attributes heart_map

BANKREF_EXTERN(heart)

extern const palette_color_t heart_palettes[4];
extern const uint8_t heart_tiles[16];

#endif
