//AUTOGENERATED FILE FROM png2asset
// Conversion args: /heart.png -map

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(heart)

const palette_color_t heart_palettes[4] = {
	RGB8(255,255,255), RGB8( 89,255,  0), RGB8(255,  0, 25), RGB8(  0,  0,  0)
	};

const uint8_t heart_tiles[16] = {
	0x00,0x00,0x00,0x66,0x66,0x99,0x7e,0x81,0x3c,0x42,0x18,0x24,0x00,0x18,0x00,0x00
	};


const unsigned char heart_map[1] = {
	32,
};
