//AUTOGENERATED FILE FROM png2asset
// Conversion args: /heart_filled.png -map -tile_origin 34

#ifndef METASPRITE_heart_filled_H
#define METASPRITE_heart_filled_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define heart_filled_TILE_ORIGIN 34
#define heart_filled_TILE_W 8
#define heart_filled_TILE_H 8
#define heart_filled_WIDTH 8
#define heart_filled_HEIGHT 8
#define heart_filled_TILE_COUNT 1
#define heart_filled_PALETTE_COUNT 1
#define heart_filled_COLORS_PER_PALETTE 4
#define heart_filled_TOTAL_COLORS 4
#define heart_filled_MAP_ATTRIBUTES 0
extern const unsigned char heart_filled_map[1];
#define heart_filled_map_attributes heart_filled_map

BANKREF_EXTERN(heart_filled)

extern const palette_color_t heart_filled_palettes[4];
extern const uint8_t heart_filled_tiles[16];

#endif
