//AUTOGENERATED FILE FROM png2asset
// Conversion args: /spell.png -sw 8 -sh 16 -o p_spell.c

#ifndef METASPRITE_p_spell_H
#define METASPRITE_p_spell_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define p_spell_TILE_ORIGIN 4
#define p_spell_TILE_W 8
#define p_spell_TILE_H 16
#define p_spell_WIDTH 8
#define p_spell_HEIGHT 16
#define p_spell_TILE_COUNT 2
#define p_spell_PALETTE_COUNT 1
#define p_spell_COLORS_PER_PALETTE 4
#define p_spell_TOTAL_COLORS 4
#define p_spell_PIVOT_X 4
#define p_spell_PIVOT_Y 8
#define p_spell_PIVOT_W 8
#define p_spell_PIVOT_H 16
extern const metasprite_t* const p_spell_metasprites[2];

BANKREF_EXTERN(p_spell)

extern const palette_color_t p_spell_palettes[4];
extern const palette_color_t e_spell_palettes[4];
extern const uint8_t p_spell_tiles[32];

#endif
