//AUTOGENERATED FILE FROM png2asset
// Conversion args: sand.png -map -tiles_only

#ifndef METASPRITE_sand_H
#define METASPRITE_sand_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sand_TILE_ORIGIN 0
#define sand_TILE_W 8
#define sand_TILE_H 8
#define sand_WIDTH 8
#define sand_HEIGHT 8
#define sand_TILE_COUNT 1
#define sand_PALETTE_COUNT 1
#define sand_COLORS_PER_PALETTE 4
#define sand_TOTAL_COLORS 4

BANKREF_EXTERN(sand)

extern const palette_color_t sand_palettes[4];
extern const uint8_t sand_tiles[16];

#endif
