//AUTOGENERATED FILE FROM png2asset
// Conversion args: sand.png -map -tiles_only

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>
#include "sand.h"

BANKREF(sand)

const palette_color_t sand_palettes[4] = {
	RGB8(246,251,187), RGB8(255,243,107), RGB8(140,132, 42), RGB8(  0,  0,  0)
	};

const uint8_t sand_tiles[16] = {
	0xf6,0x09,0xff,0x00,0xf6,0x00,0x8f,0x70,0x76,0x89,0xd9,0x06,0xef,0x10,0x5f,0x80
	};

