//AUTOGENERATED FILE FROM png2asset
// Conversion args: /shield.png -sw 16 -sh 16 -no_palettes

#ifndef METASPRITE_shield_H
#define METASPRITE_shield_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define shield_TILE_ORIGIN 30
#define shield_TILE_W 8
#define shield_TILE_H 16
#define shield_WIDTH 16
#define shield_HEIGHT 16
#define shield_TILE_COUNT 2
#define shield_PIVOT_X 8
#define shield_PIVOT_Y 8
#define shield_PIVOT_W 16
#define shield_PIVOT_H 16
extern const metasprite_t* const shield_metasprites[1];

BANKREF_EXTERN(shield)

extern const uint8_t shield_tiles[32];

#endif
