//AUTOGENERATED FILE FROM png2asset
// Conversion args: /wizard.png -sw 16 -sh 16

#ifndef METASPRITE_wizard_H
#define METASPRITE_wizard_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define wizard_TILE_ORIGIN 2
#define wizard_TILE_W 8
#define wizard_TILE_H 16
#define wizard_WIDTH 16
#define wizard_HEIGHT 16
#define wizard_TILE_COUNT 12
#define wizard_PALETTE_COUNT 1
#define wizard_COLORS_PER_PALETTE 4
#define wizard_TOTAL_COLORS 4
#define wizard_PIVOT_X 8
#define wizard_PIVOT_Y 8
#define wizard_PIVOT_W 16
#define wizard_PIVOT_H 16
extern const metasprite_t* const wizard_metasprites[4];

BANKREF_EXTERN(wizard)

extern const palette_color_t wizard_palettes[4];
extern const uint8_t wizard_tiles[192];

#endif
